platform :ios, '9.0'

target 'YMOCCodeStandard' do

pod 'MLeaksFinder'
pod 'SDWebImage'
pod 'YYWebImage'
pod 'MJRefresh'
pod 'YYModel'
pod 'WechatOpenSDK'
pod 'lottie-ios'
pod 'IQKeyboardManager'
pod 'FMDB'
pod 'ReactiveObjC', '~> 3.1.0'

end
